Set 1000 only if 100 < disk size < 1000 when querying IOPS
maximilien/softlayer-go pull request #146
Opened 2017-03-10 00:47 UTC by mattcui

For quickly addressing the issue like -> http://stackoverflow.com/questions/36395860/no-data-for-iops-while-selecting-storage-size-250gb-or-500gb-in-performance-stor

2017-03-10 12:01 UTC, mattcui commented
@maximilien I added UTs, please help review again, thanks.

2017-03-10 22:22 UTC, maximilien commented
@mattcui this is completely wrong. Let's find some time (maybe 2 hours) on Sunday night or Monday to pair on this. I think you are completely missing the point.

Do you have a [screenhero](https://screenhero.com/account/) account? If not then let me know and I'll send you an invite.

2017-03-10 22:27 UTC, maximilien requested changes
This is wrong. See my comment below. You are mixing code and tests together.

2017-03-10 22:27 UTC, maximilien commented on services/fakes/fake_softlayer_product_package.go
> +		textFixtrue = "SoftLayer_Product_Package_getItemPricesBySizeAndIops.json"
What is this `textFixtrue = "SoftLayer_Product_Package_getItemPricesBySizeAndIops.json"` in the middle of the code?

2017-03-10 22:27 UTC, maximilien commented on services/fakes/fake_softlayer_product_package.go
> +	response, _ := testhelpers.ReadJsonTestFixtures("services", textFixtrue)
Using fixtures should be only done in tests not code.

2017-03-11 01:10 UTC, mattcui commented on services/fakes/fake_softlayer_product_package.go
> +	response, _ := testhelpers.ReadJsonTestFixtures("services", textFixtrue)
I referenced [this function](https://github.com/maximilien/softlayer-go/blob/master/services/fakes/fake_softlayer_product_package.go#L17-L24) to write my code. I think I could use another way to fake functions in [softlayer_product_package.go](https://github.com/maximilien/softlayer-go/blob/master/services/softlayer_product_package.go)

2017-03-13 04:14 UTC, mattcui commented
@maximilien I rewrote this part of UT by leveraging [counterfeiter](https://github.com/maxbrunsfeld/counterfeiter) UT framework. Please help review. If you agree with this approach, I will open another bug or chore to fix the wrong UT code in [fake_softlayer_product_package.go](https://github.com/maximilien/softlayer-go/blob/master/services/fakes/fake_softlayer_product_package.go#L17-L24). Please let me know if it's not what you want yet, we could book a time to pair on this. Thanks.

2017-03-14 00:31 UTC, maximilien approved these changes
OK this is much better. I am merging for expediency, but you need to do two follow ups:
1. make sure this works for existing clients using these kind of disks. So deliver beta release and make sure results are the same
2. I would like to understand what disk sizes we will be missing with the new `selectIopsItemPriceIdOnSizebyLevel` which I feel could have an `"exact"` option when user wants to specify the exact disk size or nothing...

2017-03-14 00:31 UTC, merged